export const personalInfo = {
  name: "Tudor Crișan",
  fullName: "Todorescu-Crișan Tudor",
  title: "Software Developer and Consultant",
  yearsOfExperience: 20,
  location: "Alba Iulia, Romania",
  bio: "Software developer and consultant with 20 years of professional experience in web application development. Currently focused on React, Next.js, and Tailwind, delivering functional prototypes quickly. Previous experience in Vue.js and AngularJS projects, developing frontend for complex and scalable platforms.",
  socials: {},
  meetingUrl: "https://calendly.com/t2060891/30min?month=2026-04",
  skills: [
    { category: "Core", items: ["React", "Next.js", "Vue.js (Vue 2/3)", "TypeScript", "JavaScript (ES6+)"] },
    { category: "Styling", items: ["Tailwind CSS", "SASS/SCSS", "Styled Components", "CSS Modules"] },
    { category: "State & Logic", items: ["Pinia", "Vuex", "Redux", "React Context API", "Prisma"] },
    { category: "Tools & Backend", items: ["Node.js", "REST APIs", "Git", "Vercel", "MongoDB", "Resend", "Antigravity IDE"] },
  ],
  experience: [

    {
      company: "Kartra.com",
      role: "Senior Frontend Developer (Vue3)",
      period: "Apr 2024 – Feb 2025",
      url: "https://www.kartra.com",
      description: "Played a key role in migrating the main platform from Vue 2/jQuery to Vue 3. Developed complex frontend architectures for a SaaS ecosystem serving over 60,000 users, including landing page builders, online course platforms, and advanced lead management systems. Collaborated in a 30-engineer SCRUM environment.",
    },
    {
      company: "Zidy.com",
      role: "Strategic Technical Consultant & Lead Developer",
      period: "Oct 2022 – May 2023",
      url: "https://www.zidy.com",
      description: "Stepped in as a strategic operator to stabilize a struggling technical foundation. Rebuilt the frontend architecture (Vue 3, TS), optimized backend infrastructure for scalability, and recruited executive engineering leadership (CTOs). Transformed the product into a high-performance SaaS that reached $50k MRR and serves 2,000+ local businesses.",
    },
    {
      company: "EvobitsIT",
      role: "Senior Frontend Developer (Vue3)",
      period: "Jun 2022 – Sep 2022",
      url: "https://www.evobitsit.com",
      description: "Developed interfaces for an internal SaaS platform managing dedicated hosting services. Programmed using Vue3 and the Composition API, producing maintainable code.",
    },
    {
      company: "Kartra.com",
      role: "Senior Frontend Developer (Vue2, Vuex)",
      period: "Mar 2020 – May 2022",
      url: "https://www.kartra.com",
      description: "Developed funnel, campaign, and survey builders from scratch. Contributed to UI structure design for the main modules. Implemented the frontend using Vue2 and Vuex for a SaaS platform. Participated in the hiring process for frontend developers.",
    },
    {
      company: "Kronsoft Development",
      role: "Senior Frontend Developer (Angular 2+)",
      period: "Sep 2019 – Nov 2019",
      url: "https://www.kronsoft.ro",
      description: "Implemented frontend interfaces for medical document management systems. Developed reusable Angular 8+ components.",
    },
    {
      company: "ArtSoft Consult SRL",
      role: "Frontend Developer (AngularJS)",
      period: "Feb 2017 – May 2017",
      url: "https://www.artsoft-consult.ro",
      description: "Developed jQuery and AngularJS interfaces for the company’s outsourcing projects.",
    },
    {
      company: "Freelance via Upwork",
      role: "Frontend Developer (AngularJS)",
      period: "Jan 2016 – Dec 2016",
      url: "https://www.upwork.com",
      description: "Contributed to small and medium SaaS applications for clients from Upwork. Developed various UI/UX interfaces using AngularJS.",
    },
    {
      company: "Pet Kennel Management System",
      role: "Full-Stack AngularJS Developer",
      period: "Mar 2014 – May 2015",
      url: "https://www.pawsdogdaycare.com",
      description: "Developed the frontend in AngularJS and REST API in PHP/MySQL. Managed sprints through Redmine, hosted on AWS. Web startup project for managing pet care, grooming, and related activities.",
    },
    {
      company: "Nordlogic Software SRL",
      role: "Full-Stack Web Developer",
      period: "Dec 2012 – May 2014",
      url: "https://www.nordlogic.com",
      description: "Client projects: MiPiXi, Field-Reporting, Wittos. Tech stack: HTML, CSS, jQuery, PHP, MySQL. Gained advanced experience developing complex web applications.",
    },
    {
      company: "Internet Objects SRL",
      role: "Full-Stack Developer",
      period: "Aug 2012 – Nov 2012",
      url: "https://www.resto-in.com",
      description: "Integrated PayPal payments for the “Resto-In” platform. Developed a custom CMS in PHP/MySQL for a distributed food delivery network. First professional teamwork experience in project planning and delivery.",
    },
    {
      company: "High-school & College Projects",
      role: "Web Developer",
      period: "Jan 2007 - Jul 2012",
      url: "https://www.uab.ro",
      description: "Engineered foundational web applications for regional businesses during computer science education. Deployed custom solutions including a driving school portal, a specialized content management system (CMS), and an e-commerce platform. This independent work established an initial 5-year technical foundation in full-stack web development.",
    },
  ],
  education: {
    degree: "Bachelor’s Degree in Programming",
    institution: '"1 Decembrie 1918" University, Alba Iulia',
    period: "2009 - 2012",
  },
};
