export const personalInfo = {
  name: "Tudor Crișan",
  fullName: "Todorescu-Crișan Tudor",
  title: "Software Developer and Consultant",
  yearsOfExperience: 12,
  location: "Alba Iulia, Romania",
  bio: "Freelance developer with 12 years of professional experience in web application development. Currently focused on React, Next.js, and Tailwind, delivering functional prototypes quickly. Previous experience in Vue.js and AngularJS projects, developing frontend for complex and scalable platforms.",
  email: "tudor.crisan.webdev@gmail.com",
  socials: {
    linkedin: "https://www.linkedin.com/in/tudor-crisan-0b0ab5404/",
    facebook: "https://www.facebook.com/profile.php?id=61570750953404",
    skool: "https://www.skool.com/@tudor-friend-2124",
    whatsapp: "https://wa.me/40757754718",
    github: "https://github.com/tudor-crisan",
  },
  skills: [
    { category: "Core", items: ["React", "Next.js", "Vue.js (Vue 2/3)", "TypeScript", "JavaScript (ES6+)"] },
    { category: "Styling", items: ["Tailwind CSS", "SASS/SCSS", "Styled Components", "CSS Modules"] },
    { category: "State & Logic", items: ["Pinia", "Vuex", "Redux", "React Context API", "TanStack Query"] },
    { category: "Tools & Backend", items: ["Node.js", "Express", "REST APIs", "Git", "Docker", "Jest/Cypress"] },
  ],
  experience: [
    {
      company: "Personal project",
      role: "Web application prototype [2025] (React / Next.js / Tailwind CSS)",
      period: "2025",
      url: "https://caen-prototype.vercel.app",
      description: "Web application prototype (100% built by me). Demonstration link: https://caen-prototype.vercel.app",
    },
    {
      company: "Kartra (GDROMANIA SRL)",
      role: "Senior Frontend Developer (Vue3)",
      period: "Apr 2024 – Feb 2025",
      url: "https://www.kartra.com",
      description: "Worked together with the team on the migration the main platform from Vue2/jQuery to Vue3. Managed frontend state using Vuex, used Docker for setup, and collaborated in a cross-functional SCRUM team (~30 engineers). Developed frontend for a SaaS platform serving over 60,000 users.",
    },
    {
      company: "Zidy",
      role: "Senior Frontend Developer (Vue3, TypeScript, Pinia)",
      period: "Oct 2022 – May 2023",
      url: "https://www.zidy.com",
      description: "Built a scalable and well-structured frontend using Vue3, Pinia, Tailwind, and TypeScript. Integrated with C# microservices hosted on Azure. Developed the frontend for a SaaS CRM product currently used by approximately 2,000 users.",
    },
    {
      company: "EvobitsIT",
      role: "Senior Frontend Developer (Vue3)",
      period: "Jun 2022 – Sep 2022",
      url: "https://www.evobitsit.com",
      description: "Developed interfaces for an internal SaaS platform managing dedicated hosting services. Programmed using Vue3 and the Composition API, producing maintainable code.",
    },
    {
      company: "Kartra (Genesis Digital LLC)",
      role: "Senior Frontend Developer (Vue2, Vuex)",
      period: "Mar 2020 – May 2022",
      url: "https://www.kartra.com",
      description: "Developed funnel, campaign, and survey builders from scratch. Contributed to UI structure design for the main modules. Implemented the frontend using Vue2 and Vuex for a SaaS platform. Participated in the hiring process for frontend developers.",
    },
    {
      company: "Kronsoft Development SRL",
      role: "Senior Frontend Developer (Angular 2+)",
      period: "Sep 2019 – Nov 2019",
      url: "https://www.kronsoft.ro",
      description: "Implemented frontend interfaces for medical document management systems. Developed reusable Angular 8+ components.",
    },
    {
      company: "ArtSoft Consult SRL",
      role: "Frontend Developer (AngularJS)",
      period: "Feb 2017 – May 2017",
      url: "https://www.artsoft-consult.ro",
      description: "Developed jQuery and AngularJS interfaces for the company’s outsourcing projects.",
    },
    {
      company: "Freelance via Upwork",
      role: "Frontend Developer (AngularJS)",
      period: "Jan 2016 – Dec 2016",
      url: "https://www.upwork.com",
      description: "Contributed to small and medium SaaS applications for clients from Upwork. Developed various UI/UX interfaces using AngularJS.",
    },
    {
      company: "Pet Kennel Management System",
      role: "Full-Stack AngularJS Developer",
      period: "Mar 2014 – May 2015",
      url: "https://www.pawsdogdaycare.com",
      description: "Developed the frontend in AngularJS and REST API in PHP/MySQL. Managed sprints through Redmine, hosted on AWS. Web startup project for managing pet care, grooming, and related activities.",
    },
    {
      company: "Nordlogic Software SRL",
      role: "Full-Stack Web Developer",
      period: "Dec 2012 – May 2014",
      url: "https://www.nordlogic.com",
      description: "Client projects: MiPiXi, Field-Reporting, Wittos. Tech stack: HTML, CSS, jQuery, PHP, MySQL. Gained advanced experience developing complex web applications.",
    },
    {
      company: "Internet Objects SRL",
      role: "Full-Stack Developer",
      period: "Aug 2012 – Nov 2012",
      url: "https://www.resto-in.com",
      description: "Integrated PayPal payments for the “Resto-In” platform. Developed a custom CMS in PHP/MySQL for a distributed food delivery network. First professional teamwork experience in project planning and delivery.",
    },
  ],
  education: {
    degree: "Bachelor’s Degree in Programming",
    institution: '"1 Decembrie 1918" University, Alba Iulia',
    period: "2009 - 2012",
  },
};
