export const personalInfo = {
  name: "Tudor Crișan",
  fullName: "Todorescu-Crișan Tudor",
  title: "Software Developer and Consultant",
  yearsOfExperience: 12,
  location: "Alba Iulia, Romania",
  bio: "Software developer and consultant with almost 20 years of professional experience in web application development. Currently focused on React, Next.js, and Tailwind, delivering functional prototypes quickly. Previous experience in Vue.js and AngularJS projects, developing frontend for complex and scalable platforms.",
  email: "tudor.crisan.webdev@gmail.com",
  socials: {
    linkedin: "https://www.linkedin.com/in/tudor-crisan-0b0ab5404/",
    facebook: "https://www.facebook.com/profile.php?id=61570750953404",
    skool: "https://www.skool.com/@tudor-friend-2124",
    whatsapp: "https://wa.me/40757754718",
    github: "https://github.com/tudor-crisan",
  },
  skills: [
    { category: "Core", items: ["React", "Next.js", "Vue.js (Vue 2/3)", "TypeScript", "JavaScript (ES6+)"] },
    { category: "Styling", items: ["Tailwind CSS", "SASS/SCSS", "Styled Components", "CSS Modules"] },
    { category: "State & Logic", items: ["Pinia", "Vuex", "Redux", "React Context API", "Prisma"] },
    { category: "Tools & Backend", items: ["Node.js", "REST APIs", "Git", "Vercel", "MongoDB", "Resend", "Antigravity IDE"] },
  ],
  experience: [
    {
      company: "VibeSniper CRM",
      role: "Lead Architect & Developer",
      period: "2026",
      url: "https://vibesniper-crm.vercel.app/pitch",
      description: "Architected and built a high-value lead intelligence platform designed for high-stakes outreach. Integrated advanced lead scoring and 'Sniper Intelligence' modules to help users target top-tier founders and CEOs. Built with Next.js, Tailwind CSS, and Framer Motion.",
    },
    {
      company: "Wholesale Systems Architect",
      role: "Systems Consultant & Developer",
      period: "2026",
      url: "https://www.wholesale-systems.online/",
      description: "Builds custom automation and software systems for high-volume wholesalers. Specialized in SMS deliverability, CRM optimization (API integrations for Podio/REsimpli), and AI lead nurturing systems to eliminate manual follow-up chaos.",
    },
    {
      company: "Cold Calling CRM",
      role: "Full-Stack Developer",
      period: "2026",
      url: "https://coldcalling-crm.vercel.app",
      description: "Developed a specialized bilingual CRM optimized for high-speed cold calling operations. Features real-time lead pipeline management, automated status tracking, and performance analytics built with Next.js and Tailwind CSS.",
    },
    {
      company: "CTO Outreach Dashboard",
      role: "Lead Developer",
      period: "2026",
      url: "https://crunchbase-outreach.vercel.app",
      description: "An intelligent outreach platform integrating Crunchbase data to target high-tier decision makers. Features automated lead scoring, personalized message drafting for Founders/CTOs, and a research-centric UI for deep business intelligence.",
    },
    {
      company: "ShutterConnect",
      role: "Lead Architect & Developer",
      period: "2025",
      url: "https://app.megashoot.ro",
      description: "A comprehensive management system for professional photographers. Streamlines the entire workflow from shoot scheduling and client communication to digital asset delivery, featuring a high-performance React dashboard and automated client portals.",
    },
    {
      company: "CAEN Prototype",
      role: "Lead Architect & Developer",
      period: "2025",
      url: "https://caen-prototype.vercel.app",
      description: "Developed an intelligent search and discovery platform for Romanian CAEN codes, designed to simplify business registration and classification processes. Built with Next.js and Tailwind CSS, featuring high-speed filtering and a modern UX for navigating complex economic activity data.",
    },
    {
      company: "Kartra.com",
      role: "Senior Frontend Developer (Vue3)",
      period: "Apr 2024 – Feb 2025",
      url: "https://www.kartra.com",
      description: "Played a key role in migrating the main platform from Vue 2/jQuery to Vue 3. Developed complex frontend architectures for a SaaS ecosystem serving over 60,000 users, including landing page builders, online course platforms, and advanced lead management systems. Collaborated in a 30-engineer SCRUM environment.",
    },
    {
      company: "Zidy.com",
      role: "Senior Frontend Developer (Vue3, TypeScript, Pinia)",
      period: "Oct 2022 – May 2023",
      url: "https://www.zidy.com",
      description: "Built the frontend for an AI-powered business growth platform that automates lead conversion and review gathering via SMS and Voice 24/7. Developed a scalable dashboard used by over 2,000 businesses to track performance and manage customer conversations in real-time.",
    },
    {
      company: "EvobitsIT",
      role: "Senior Frontend Developer (Vue3)",
      period: "Jun 2022 – Sep 2022",
      url: "https://www.evobitsit.com",
      description: "Developed interfaces for an internal SaaS platform managing dedicated hosting services. Programmed using Vue3 and the Composition API, producing maintainable code.",
    },
    {
      company: "Kartra.com",
      role: "Senior Frontend Developer (Vue2, Vuex)",
      period: "Mar 2020 – May 2022",
      url: "https://www.kartra.com",
      description: "Developed funnel, campaign, and survey builders from scratch. Contributed to UI structure design for the main modules. Implemented the frontend using Vue2 and Vuex for a SaaS platform. Participated in the hiring process for frontend developers.",
    },
    {
      company: "Kronsoft Development",
      role: "Senior Frontend Developer (Angular 2+)",
      period: "Sep 2019 – Nov 2019",
      url: "https://www.kronsoft.ro",
      description: "Implemented frontend interfaces for medical document management systems. Developed reusable Angular 8+ components.",
    },
    {
      company: "ArtSoft Consult SRL",
      role: "Frontend Developer (AngularJS)",
      period: "Feb 2017 – May 2017",
      url: "https://www.artsoft-consult.ro",
      description: "Developed jQuery and AngularJS interfaces for the company’s outsourcing projects.",
    },
    {
      company: "Freelance via Upwork",
      role: "Frontend Developer (AngularJS)",
      period: "Jan 2016 – Dec 2016",
      url: "https://www.upwork.com",
      description: "Contributed to small and medium SaaS applications for clients from Upwork. Developed various UI/UX interfaces using AngularJS.",
    },
    {
      company: "Pet Kennel Management System",
      role: "Full-Stack AngularJS Developer",
      period: "Mar 2014 – May 2015",
      url: "https://www.pawsdogdaycare.com",
      description: "Developed the frontend in AngularJS and REST API in PHP/MySQL. Managed sprints through Redmine, hosted on AWS. Web startup project for managing pet care, grooming, and related activities.",
    },
    {
      company: "Nordlogic Software SRL",
      role: "Full-Stack Web Developer",
      period: "Dec 2012 – May 2014",
      url: "https://www.nordlogic.com",
      description: "Client projects: MiPiXi, Field-Reporting, Wittos. Tech stack: HTML, CSS, jQuery, PHP, MySQL. Gained advanced experience developing complex web applications.",
    },
    {
      company: "Internet Objects SRL",
      role: "Full-Stack Developer",
      period: "Aug 2012 – Nov 2012",
      url: "https://www.resto-in.com",
      description: "Integrated PayPal payments for the “Resto-In” platform. Developed a custom CMS in PHP/MySQL for a distributed food delivery network. First professional teamwork experience in project planning and delivery.",
    },
    {
      company: "High-school & College Projects",
      role: "Web Developer",
      period: "Jan 2007 - Jul 2012",
      url: "https://www.uab.ro",
      description: "While in high-school for computer science and college I've developed small projects for local companies in Alba Iulia, from drivers school website, bridge CMS and fireworks online shop, plus others that helped me gained 5 years experience in web development",
    },
  ],
  education: {
    degree: "Bachelor’s Degree in Programming",
    institution: '"1 Decembrie 1918" University, Alba Iulia',
    period: "2009 - 2012",
  },
};
